### ISSUE TITLE
Tax evidence requests

### ISSUE THREAD

**Issue by jdmnd** [0ctobat/octobat-npm#1]
As far as I can tell, this library doesn't currently support the POST endpoint located at `https://apiv2.octobat.com/tax_evidence_requests`. 
See http://v2apidoc.octobat.com/?ruby#request-a-tax-evidence
Is there a motivation for excluding it? If not, is it a planned feature?

Thanks,
John

**Comment by zuuno** [comment]
Hi John,

The update has been performed.
Using v2.0.1 you can now access the requested method.

Best,
Gaultier
