### ISSUE TITLE
tax_evidence_requests/for_supplier support

### ISSUE THREAD

**Issue by leedavidcs** [0ctobat/octobat-npm#6]
Does this package support the `POST tax_evidence_requests/for_supplier` support endpoint from the v2 docs?

**Comment by 0ctobat** [comment]
Hello,
We just added support for this endpoint on the latest release (`2.0.5`).

Does that help?
Thanks

**Comment by leedavidcs** [comment]
> Hello,
> We just added support for this endpoint on the latest release (`2.0.5`).
> 
> Does that help?
> Thanks

Yes, that works. Thanks for the quick update!
